### PR TITLE
#86 - Document Default View

### PR DESCRIPTION
**Pull request by dleadbetter**
This pull request adds the `document_view_right` column to `projects` and updates the impacted `tables` and `functions`.

### CODE REVIEW

**Review by rsimon — APPROVED** [review]
Not that I can say much about the DB schema. (It's @lwjameson realm :-) But this looks good to me - with one question already mentioned in the client PR: I wonder if we really need the 'closed' state, or should simply make the column nullable?

**Review by lwjameson — APPROVED** [review]
This looks good.

**Comment by lwjameson** [comment]
In terms of @rsimon comment, I could go either way.  But I am sometimes cautious about the lack of value (null) having more meaning beyond 'false'/'undefined'.  If the desire is for it to be closed, I see usefulness in that.  You never know when the default behavior might change and an explicit 'closed' could override that.

**Comment by rsimon** [comment]
@lwjameson that makes sense - agreed!

**Pull request merged**
